name: Build containers

on:
  push:
    branches: [main]
    paths:
    - 'containers/**'

jobs:
  build-caddy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract version
      run: echo VERSION=$(grep -oP "caddy:\K.+" containers/caddy/Dockerfile | tail -n1) >> $GITHUB_ENV

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}/caddy
        tags: ${{ env.VERSION }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: containers/caddy
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
